"""
Local fallback answer generator used when OpenRouter is unavailable.
Streams a helpful, honest response token by token.
"""
import asyncio
from collections.abc import AsyncGenerator


async def stream_fallback(prompt: str) -> AsyncGenerator[str, None]:
    """Yield a helpful fallback answer token by token."""
    message = (
        "This response is generated by NInsideN's local fallback because the "
        "model provider is unavailable or not configured. "
        "To use a real language model, add your OPENROUTER_API_KEY to the "
        "environment variables.\n\n"
        "Here is what the trace pipeline showed about your prompt:\n\n"
        "Your prompt was received, normalised, and tokenised. Intent was detected "
        "and a retrieval query was generated. The local demo knowledge base was "
        "searched and relevant context chunks were selected. The context window was "
        "assembled. At this point, a live model call would have been made to the "
        "configured OpenRouter model, which would have produced a real streaming "
        "answer based on the context.\n\n"
        "Configure OPENROUTER_API_KEY to see a real AI-generated response through "
        "the full NInsideN trace pipeline."
    )
    for word in message.split(" "):
        yield word + " "
        await asyncio.sleep(0.03)
