"""
OpenRouter streaming client.
Calls the OpenRouter chat completions endpoint with streaming enabled.
Falls back gracefully if the API key is not configured.
"""
import json
from collections.abc import AsyncGenerator
from typing import Any

import httpx

from app.config import settings

OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"

SYSTEM_PROMPT = (
    "You are NInsideN's educational AI assistant. "
    "Explain AI concepts clearly, accurately, and concisely. "
    "Do not invent or reveal private model chain-of-thought. "
    "Base your response on the supplied context. "
    "If the context is labelled as local demo knowledge, do not claim it is "
    "live or real-time web data. "
    "Keep responses focused and educational, 200–400 words."
)


async def stream_openrouter(
    prompt: str,
    context_chunks: list[dict[str, Any]],
) -> AsyncGenerator[str, None]:
    """
    Stream answer tokens from OpenRouter.
    If no API key is configured, delegate to the mock fallback.
    """
    if not settings.openrouter_configured:
        async for token in _mock_stream(prompt, context_chunks):
            yield token
        return

    context_text = _format_context(context_chunks)
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {
            "role": "user",
            "content": (
                f"Context (demo/local retrieval layer):\n{context_text}\n\n"
                f"Question: {prompt}"
            ),
        },
    ]

    try:
        async with httpx.AsyncClient(timeout=60) as client:
            async with client.stream(
                "POST",
                OPENROUTER_API_URL,
                headers={
                    "Authorization": f"Bearer {settings.openrouter_api_key}",
                    "HTTP-Referer": settings.site_url,
                    "X-Title": settings.site_name,
                    "Content-Type": "application/json",
                },
                json={
                    "model": settings.openrouter_model,
                    "messages": messages,
                    "stream": True,
                    "max_tokens": 600,
                },
            ) as response:
                if response.status_code != 200:
                    error_body = await response.aread()
                    raise RuntimeError(
                        f"OpenRouter returned HTTP {response.status_code}: "
                        f"{error_body.decode()[:200]}"
                    )

                async for line in response.aiter_lines():
                    if not line.startswith("data: "):
                        continue
                    raw = line[6:].strip()
                    if raw == "[DONE]":
                        break
                    try:
                        chunk = json.loads(raw)
                        delta = chunk["choices"][0]["delta"]
                        token = delta.get("content", "")
                        if token:
                            yield token
                    except (json.JSONDecodeError, KeyError, IndexError):
                        continue

    except httpx.TimeoutException:
        raise RuntimeError("OpenRouter request timed out.")
    except httpx.NetworkError as exc:
        raise RuntimeError(f"Network error reaching OpenRouter: {exc}") from exc


def _format_context(chunks: list[dict[str, Any]]) -> str:
    if not chunks:
        return "No context retrieved."
    parts = []
    for i, chunk in enumerate(chunks, 1):
        parts.append(
            f"[{i}] {chunk.get('title', 'Untitled')} "
            f"(source: {chunk.get('type', 'unknown')})\n"
            f"{chunk.get('snippet', '')}"
        )
    return "\n\n".join(parts)


async def _mock_stream(
    prompt: str,
    context_chunks: list[dict[str, Any]],
) -> AsyncGenerator[str, None]:
    """
    Polished mock streaming answer used when no API key is set.
    Returns an educational response token by token.
    """
    import asyncio

    context_titles = [c.get("title", "") for c in context_chunks[:3]]
    context_note = (
        f" (based on local demo context: {', '.join(context_titles)})"
        if context_titles
        else ""
    )

    answer = (
        f"This response is generated by NInsideN's local fallback — the model provider "
        f"is not configured or unavailable{context_note}.\n\n"
    )

    # Generate a topic-aware fallback paragraph
    topic_answers: dict[str, str] = {
        "neural": (
            "Neural networks learn by adjusting weights through backpropagation. "
            "During the forward pass, inputs travel through layers of neurons, each applying "
            "a weighted sum followed by an activation function. The loss measures how far the "
            "prediction is from the truth. Backpropagation then computes gradients using the "
            "chain rule and an optimizer like Adam updates every weight to reduce that loss. "
            "This cycle repeats across many training examples until the network generalises well."
        ),
        "backprop": (
            "Backpropagation is the algorithm that makes neural networks learn. It applies the "
            "chain rule of calculus to propagate the gradient of the loss function backwards "
            "through every layer. Each weight receives a gradient signal telling it how much "
            "it contributed to the error. The optimizer then nudges each weight in the "
            "direction that reduces the loss. Without backpropagation, training deep networks "
            "efficiently would be computationally infeasible."
        ),
        "rag": (
            "Retrieval-Augmented Generation (RAG) enhances AI responses by first retrieving "
            "relevant documents from a knowledge base, then supplying them as context to the "
            "language model. The model reads this context when generating its answer, allowing "
            "it to reference specific facts without memorising them during training. "
            "The retrieval step typically uses dense vector embeddings and approximate "
            "nearest-neighbour search. This makes RAG systems accurate on private or recent data."
        ),
        "token": (
            "LLMs don't process raw text — they work with tokens, sub-word units produced by "
            "algorithms like Byte-Pair Encoding. A tokeniser splits 'backpropagation' into "
            "something like ['back', 'prop', 'agation']. Each token maps to a high-dimensional "
            "embedding vector. The model processes these vectors, not characters or words. "
            "Token count determines how much text fits in the context window and how much "
            "inference costs."
        ),
        "transformer": (
            "The Transformer architecture (2017) revolutionised NLP by replacing recurrence "
            "with self-attention. Each token attends to every other token in the sequence, "
            "learning which parts are most relevant. Multiple attention heads capture different "
            "types of relationships. GPT-family models stack many decoder blocks, each refining "
            "the token representations. This parallel attention mechanism is what makes large "
            "language models both powerful and efficient to train on modern hardware."
        ),
        "stream": (
            "Language models generate text one token at a time. Streaming lets the application "
            "display each token immediately rather than waiting for the full response. The "
            "server sends chunks over Server-Sent Events (SSE) or WebSockets. The client "
            "appends each token to the displayed text, creating the familiar typewriter effect. "
            "This improves perceived performance significantly — users see content within "
            "milliseconds rather than waiting several seconds for a complete response."
        ),
    }

    prompt_lower = prompt.lower()
    selected = next(
        (text for key, text in topic_answers.items() if key in prompt_lower),
        (
            "AI systems process your prompt through several layers: normalisation, tokenisation, "
            "intent detection, retrieval, context building, and finally a model call that streams "
            "tokens back. Each step is observable at the application level — which is exactly "
            "what NInsideN visualises. The model itself is a black box, but the pipeline "
            "around it is fully transparent and traceable."
        ),
    )

    full_response = answer + selected
    words = full_response.split(" ")
    for i, word in enumerate(words):
        token = word if i == len(words) - 1 else word + " "
        yield token
        await asyncio.sleep(0.04)
